export const SprintList = {
  sprints: [
    {
      id: "sprint_ABC123",
      name: "Sprint 1",
      startDate: "2024-02-01",
      endDate: "2024-02-14",
      tasks: [
        {
          id: "task_1A",
          title: "Implement user authentication",
          description: "Create login and registration functionality for users",
          status: "InProgress",
          priority: "High",
          estimation: 8,
          assignee: "John Doe",
        },
        {
          id: "task_2B",
          title: "Design homepage UI",
          description: "Create wireframes and mockups for the homepage",
          status: "ToDo",
          priority: "Medium",
          estimation: 5,
          assignee: "Jane Smith",
        },
        {
          id: "task_3C",
          title: "Implement backend API",
          description: "Set up backend endpoints for data retrieval",
          status: "ToDo",
          priority: "Medium",
          estimation: 6,
          assignee: "Chris Brown",
        },
        {
          id: "task_4D",
          title: "Write unit tests",
          description: "Develop unit tests for code coverage",
          status: "ToDo",
          priority: "Low",
          estimation: 4,
          assignee: "Eva Green",
        },
        {
          id: "task_5E",
          title: "Refactor database schema",
          description: "Optimize database structure for performance",
          status: "ToDo",
          priority: "High",
          estimation: 7,
          assignee: "Max Johnson",
        },
      ],
    },
    {
      id: "sprint_XYZ789",
      name: "Sprint 2",
      startDate: "2024-02-15",
      endDate: "2024-02-28",
      tasks: [
        {
          id: "task_6F",
          title: "Implement search feature",
          description: "Add search functionality to the application",
          status: "InProgress",
          priority: "High",
          estimation: 6,
          assignee: "Samuel Williams",
        },
        {
          id: "task_7G",
          title: "Design database schema",
          description: "Create a database schema for the new features",
          status: "ToDo",
          priority: "Medium",
          estimation: 5,
          assignee: "Emma Watson",
        },
        {
          id: "task_8H",
          title: "Implement user profile page",
          description:
            "Create a profile page for users to view and edit their information",
          status: "ToDo",
          priority: "High",
          estimation: 8,
          assignee: "John Doe",
        },
        {
          id: "task_9I",
          title: "Fix UI bugs",
          description: "Resolve visual glitches and inconsistencies in the UI",
          status: "ToDo",
          priority: "Medium",
          estimation: 4,
          assignee: "Julia Roberts",
        },
      ],
    },
  ],
};
